# Modelado flexible con Matérn {#secModeling}

Se podría objetar que el modelo de Matérn no es lo suficientemente flexible para muchas aplicaciones estadísticas, ya que está limitado a campos aleatorios con valores escalares que son estacionarios, isotrópicos y gaussianos. Sin embargo, el modelo Matérn también es un componente importante para muchos modelos más sofisticados, algunos de los cuales se describirán a continuación. Ésta es una literatura rica y nuestra discusión es necesariamente sucinta; se puede encontrar una versión ampliada de esta sección en el Apéndice [10](#Appendix) del Material complementario.

## Campos aleatorios con valores escalares

Comencemos analizando modelos para campos aleatorios con valores escalares que se basan en el modelo de Matérn. Tenga en cuenta que se pueden introducir trivialmente funciones medias distintas de cero en el modelo de Matérn, o combinar (de forma aditiva o multiplicativa) núcleos para obtener un núcleo potencialmente más expresivo; No nos detendremos en ninguno de los dos puntos.

Para relajar el supuesto de isotropía del modelo de Matérn, [7] considera mezclas de escala que tienen en cuenta direcciones preferenciales en las que se desarrolla la dependencia espacial. Por otro lado, el caso de los modelos espacio-temporales requiere un tratamiento especial, y las versiones no separables del núcleo Matérn se describen en [62] [178].

El supuesto de estacionariedad se relajó de manera paramétrica en [119] y luego de manera no paramétrica en [132]. En [170] se informó sobre un intento de lograr un equilibrio entre la manejabilidad computacional de los modelos paramétricos y la flexibilidad de los modelos no paramétricos, quien propuso *input warping* para transformar las entradas al modelo Matérn utilizando una red neuronal.

La suposición gaussiana se puede relajar mediante *deformación de salida*, es decir, transformación de la forma $\tilde{Z}(\boldsymbol{x}) = w(Z(\boldsymbol{x}))$ donde $w(\cdot)$ es un mapa no lineal de $\mathbb{R}^d$ a $\mathbb{R}^d$ . La función de covarianza de $\tilde{Z}$ no será Matérn en general, cuando la función de covarianza de $Z$ sea Matérn, pero si $w$ es suficientemente regular, entonces las propiedades de suavidad de $Z$ se transfieren a $\tilde{Z}$ . La pregunta de si existen procesos no gaussianos cuya función de covarianza sea, sin embargo, de clase Matérn fue respondida positivamente en [1]. [174] ha propuesto campos aleatorios *transgaussianos* con función de covarianza Matérn. [29] y posteriormente [164] proporcionaron construcciones basadas en SPDE para campos Matérn no gaussianos. Las clases generales de campos no gaussianos con covarianza $g({\cal M}_{\nu,\alpha})$ , para $g(\cdot)$ , una función adecuada que preserva las propiedades positivas de definición y suavidad del modelo de Matérn, han sido proporcionadas, por ejemplo, por [120] [173; 24; 113].

Una extensión importante del modelo Matérn, que ha recibido atención reciente, son los campos aleatorios en espacios para los cuales las nociones clásicas de suavidad no están bien definidas. Por ejemplo, [9] considere gráficos con bordes euclidianos, equipados con la distancia geodésica sobre el gráfico o la métrica de resistencia. [112] proporciona una generalización de esta configuración considerando espacios cuasimétricos. [Bolin, Simas y Wallin (2022)](https://doi.org/10.48550/arXiv.2205.06163) adopta un enfoque diferente para crear campos aleatorios con su estructura de covarianza en gráficos métricos. La versión espacio-temporal del modelo de Matérn, para gráficos con aristas euclidianas, ha sido considerada por [155] y [127]. Estos esfuerzos amplían considerablemente la aplicabilidad del modelo Matérn.

La función de covarianza de Matérn decae exponencialmente con la distancia, lo que puede resultar inadecuado para modelar procesos que implican una larga memoria. Se han desarrollado varios enfoques para modificar las colas de la función de correlación de Matérn preservando al mismo tiempo muchas de sus características deseables; los describimos en la sección [7](#surr).

[68] considera campos aleatorios gaussianos definidos para las celosías $\mathbb{Z}^d$ con una función de covarianza que es la restricción de la covarianza de Matérn a $\mathbb{Z}^d$ . El espectro resultante es una versión suavizada de la densidad espectral asociada con la covarianza de Matérn. Para esta situación específica, la aproximación SPDE puede sobreestimar la escala, $\alpha$ . Sin embargo, no está claro cómo se extiende este mensaje a los campos gaussianos que se indexan continuamente en $\mathbb{R}^d$ .

## Campos aleatorios con valores vectoriales

Ha habido una gran cantidad de enfoques relacionados con el modelado espacial multivariado y se remite al lector a [60]. Aquí, la función de covarianza isotrópica $\boldsymbol{K}: [0,\infty) \to \mathbb{R}^{p \times p}$ tiene un valor matricial. Los elementos de la diagonal, $K_{ii}$ , se denominan funciones de *autocovarianza*, y los elementos $K_{ij}$ , $i\ne j$ , se denominan funciones de *covarianza cruzada*. [64] propuso un modelo Matérn multivariado

$$
\label{stma}
K_{ij}(x) = \sigma_{ii} \sigma_{jj} \rho_{ij} {\cal M}_{\nu_{ij},\alpha_{ij}} (x), \qquad x \ge 0, \quad
$$

dónde $\sigma_{ii}^2$ es la varianza de $Z_i$ , el $i$ ésimo componente de un campo aleatorio multivariado en $\mathbb{R}^p$ , y $\rho_{ij}$ es el coeficiente de correlación colocado. Hay restricciones en los parámetros. $\nu_{ij}, \alpha_{ij}$ y $\rho_{ij}$ requerido para asegurar una definición positiva y, a menudo, las restricciones sobre los coeficientes de correlaciones colocadas $\rho_{ij}$ son bastante estrictos. Esta última observación ha motivado enfoques alternativos, y se remite al lector a[11]y más recientemente a[54]. Las extensiones a las estructuras multivariadas espacio-temporales de Matérn han sido proporcionadas por[6]y a través de un enfoque técnico por[125]. Las funciones multivariadas no estacionarias de Matérn han sido propuestas por[88]. Los modelos multivariados de Matérn con efecto *hoyuelo* han sido estudiados por[4]; un 'hoyuelo' en un modelo de covarianza espacio-temporal se refiere al caso en el que $\text{Cov}( Z(\boldsymbol{x}, t), Z(\boldsymbol{x}', t') )$ es más grande que $\text{Cov}(( Z(\boldsymbol{x}, t), Z(\boldsymbol{x}', t))$ , que requiere un tratamiento matemático especial.

El modelado multivariado de Matérn en gráficos ha sido investigado recientemente en [51], quien propone una clase de procesos gaussianos gráficos multivariados a través de *costuras*, una construcción que obtiene funciones de covarianza multivariadas del gráfico y garantiza independencia condicional a nivel de proceso entre variables. Cuando se combina con el modelo de Matérn, la unión produce un proceso gaussiano multivariado cuyos componentes univariados son procesos gaussianos de Matérn y que concuerda con la independencia condicional a nivel de proceso como lo especifica el modelo gráfico. La unión puede ofrecer enormes ganancias computacionales y reducción de dimensiones de parámetros. [97] propuso recientemente un enfoque ingenioso para la construcción del proceso gaussiano que involucra la función de covarianza de Matérn, quien consideró un espacio de producto que involucra el espacio euclidiano de dimensión $d$ cruzando un conjunto abstracto que permite indexar etiquetas de grupos.

## Direcciones, formas y curvas

El modelo de Matérn tiene un papel importante en el estudio de procesos direccionales, formalizando [18] las nociones de *procesos en diferencias finitas* direccionales y *procesos derivados direccionales* con especial énfasis en el modelo de Matérn. El modelo Matérn también tiene un papel en el análisis de formas, donde [16] introdujo *wombling bayesiano* para medir gradientes *espaciales* relacionados con curvas a través de límites de 'wombling', y el enfoque se llevó más allá en [71]. Las propiedades de suavidad del modelo Matérn se adaptan perfectamente a una estructura de este tipo. [131] ha propuesto enfoques de modelado de gradientes *temporales* utilizando el modelo Matérn. En relación con estos enfoques, el parámetro de suavidad $\nu$ del modelo Matérn juega un papel central en el artículo reciente de [71], quien analiza superficies aleatorias para explicar la dependencia latente dentro de una variable de respuesta de interés.

Esto representa un breve recorrido por las aplicaciones *estadísticas* del modelo Matérn, pero su alcance va mucho más allá de las estadísticas, y a continuación exploramos la importancia del modelo Matérn en campos relacionados.
