# Mejoras del Modelo Matérn {#surr}

[]{#sec6 label="sec6"}

Esta sección describe *mejoras* del modelo Matérn; funciones de covarianza que comparten (al menos parcialmente) las propiedades locales del modelo Matérn al tiempo que proporcionan características y funcionalidades adicionales. Aquí presentamos primero los modelos uno por uno, con comentarios críticos sobre sus características remitidos a la Sección [8](#sec7).

## Modelos con soporte compacto {#sec-comp-sup}

Los modelos de covarianza con soporte compacto tienen una larga historia que se remonta a [12], quien propuso el núcleo

$$
\label{askey}.
{\cal A}_{\mu,\beta}(x) = \left ( 1- \frac{x}{\beta}\right )_+^{\mu}, \qquad x \ge 0,
$$

con $\beta$ y $\mu$ siendo estrictamente positivo, y donde $(x)_+=\max(0,x)$ es la *potencia truncada*. En ese trabajo se demostró que ${\cal A}_{\mu,\beta}$ pertenece a $\Phi_d$ para todo $\beta>0$ si y solo si $\mu \ge (d+1)/2$ . Es evidente que el mapeo $\boldsymbol{x} \mapsto {\cal A}_{\mu,\beta}(\|\boldsymbol{x}\|)$ se apoya de forma compacta sobre una bola con radio $\beta$ incrustado en $\mathbb{R}^d$ . Como resultado, las matrices de covarianza contienen entradas exactas de cero siempre que los estados asociados $\boldsymbol{x}_i$ y $\boldsymbol{x}_j$ satisfacen $\|\boldsymbol{x}_i - \boldsymbol{x}_j\| \geq \beta$ ; Las ventajas computacionales de esta dispersidad se analizan con más detalle en la sección [8.5].

[165] aplicó el enfoque *montée* y *descente* [110] de Matheron a las funciones Askey, obteniendo funciones de covarianza soportadas de forma compacta con suavidad de orden superior que son polinomios truncados como funciones de $\|\boldsymbol{x}\|$ . Esta estrategia no pudo generar espacios de Sobolev de orden entero en dimensiones de espacio par, un problema que se resolvió en [136], quien identificó las funciones de Wendland "faltantes". [62] proporcionó una vista unificada de las funciones de Wendland. [175] proporcionó las condiciones necesarias y suficientes para una clase general que abarca funciones Wendland tanto ordinarias como faltantes. [38] proporcionó una generalización de las funciones de Wendland, con suficientes condiciones paramétricas que permiten que la nueva clase pertenezca a $\Phi_d$ para un $d$ determinado. Esas funciones, denominadas funciones *Buhmann*, fueron estudiadas luego por [176] y posteriormente por [177] [129] y [56]. [76] y [40] han estudiado representaciones y propiedades alternativas de las funciones de Wendland. También se han desarrollado extensiones de las funciones de Wendland a multivariado [124; 46], espacio-temporal [123] y procesos no estacionarios [89].

Sigue una discusión más técnica, en la que presentamos dos clases adicionales de funciones de correlación con soporte compacto, cada una de las cuales será el tema de discusión en la Sección [8](#sec7).

**1.** La familia generalizada Wendland ( ${\cal GW}$ ) [61; 176] contiene funciones de correlación con soporte compacto que, como en el modelo de Matérn, admiten una parametrización continua de suavidad del campo aleatorio gaussiano subyacente. El modelo ${\cal GW}_{\kappa,\mu,\beta}$ depende de los parámetros $\kappa \ge 0$ y $\mu,\beta>0$ a través de la identidad

$$
\begin{gathered}
 \label{WG4*}
{\cal GW}_{\kappa,\mu, \beta}(x)\\= 
 \frac{\Gamma(\kappa)\Gamma(2\kappa+\mu+1)}{\Gamma(2\kappa)\Gamma(\kappa+\mu+1)2^{\mu+1}} {\cal A}_{\kappa+\mu,\beta^2} \left( x^2 \right) \\
 \times {}_2F_1\left(\frac{\mu}{2},\frac{\mu+1}{2};\kappa+\mu+1;{\cal A}_{1,\beta^2} \left( x^2 \right) \right),
 \end{gathered}
$$

dónde $\mu\geq (d+1)/2+\kappa$ es necesario para ${\cal GW}_{\kappa,\mu, \beta}$ pertenecer a la clase $\Phi_d$ y ${}_2F_1(a,b,c,\cdot)$ es la función hipergeométrica gaussiana[2]. Rutas de muestra de la ${\cal GW}_{\kappa,\mu, \beta}$ modelo son $k$ multiplicada por la media cuadrática diferenciable, en cualquier dirección, si y sólo si $\kappa>k-1/2$ [61], de modo que $\kappa$ juega el papel del parámetro de suavidad en este modelo. Cuando $\kappa=k \in \mathbb{N}$ , ${\cal GW}_{k,\mu, \beta}$ factores en el producto de la función Askey ${\cal A}_{\mu+k,\beta}$ con un polinomio de grado $k$ . Este modelo incluye las funciones Wendland ( $\kappa=k$ , un número entero positivo), así como las funciones de Wendland que faltan ( $\kappa=k+1/2$ ). Teorema 1(3) en[25]implica que el RKHS inducido por ${\cal GW}_{\kappa/2-(d+1)/4,\mu,\beta}$ , con $\kappa \ge (d+1/2)$ , es norma equivalente al espacio de Sobolev $W_{2}^{\kappa}(\mathbb{R}^d)$ .

**2.** La familia [53] hipergeométrica de Gauss ( $\mathcal{GH}$ ) se define como

$$
\begin{gathered}
 \label{emery}
 \mathcal{GH}_{\kappa,\delta,\gamma,\beta}(x) \\ = \frac{\Gamma(\delta-d/2)\Gamma(\gamma-d/2)}{\Gamma(\delta-\kappa+\gamma - d/2) \Gamma(\kappa-d/2)} \\ \times {\cal A}_{\delta-\kappa + \gamma-d/2+1,\beta^2} \left( x^2 \right)\times\\
{}_2F_1\left( \delta-\kappa; \gamma-\kappa; \delta-\kappa + \gamma -d/2;
{\cal A}_{1,\beta^2} (x^2) 
 \right).
 \end{gathered}
$$

Este modelo tiene cuatro parámetros y pertenece a la clase. $\Phi_d$ por cada positivo $\beta$ provided $\kappa>d/2$ con

$$
2(\delta-\kappa)(\gamma-\kappa) \geq \kappa, \quad \text{y} \quad
2(\delta+\gamma)\geq 6\kappa+1.
$$

Rutas de muestra de la $\mathcal{GH}_{\kappa,\delta,\gamma,\beta}$ modelo son $\lceil k/2\rceil$ multiplicada por la media cuadrática diferenciable, en cualquier dirección, si y sólo si $\kappa>(k+d)/2$ . El parámetro $\kappa$ también controla la suavidad de las muestras de este modelo.

La importancia de los modelos $\mathcal{GW}$ y $\mathcal{GH}$ se analiza en la sección [8](#sec7).

## Modelos con decaimiento polinómico

Los modelos de correlación con desintegración polinomial, como el modelo generalizado de Cauchy [65] o los modelos de Dagum [22], pueden resultar útiles al modelar datos con dependencia de largo alcance. Sin embargo, al utilizar estos modelos de correlación se pierde control sobre la diferenciabilidad de las trayectorias muestrales, una propiedad clave del modelo de Matérn. [106] propuso recientemente una modificación de la clase Matérn que permite la desintegración polinomial, manteniendo al mismo tiempo las propiedades locales del modelo Matérn convencional. La función de correlación asociada a este modelo viene dada por

$$
\label{anciano}
 \mathcal{CH}_{\nu,\eta,\beta}(x) = \frac{\Gamma(\nu+\eta)}{\Gamma(\nu)} \, \mathcal{U}\left( \eta,1-\nu, \nu \left(\frac{x}{\beta} \right)^2 \right), \; x\geq 0,
$$

dónde $\mathcal{U}$ es la función hipergeométrica confluente de segundo tipo[2]. Here $\nu>0$ controla la diferenciabilidad cuadrática media cerca del origen, como en el caso de Matérn, mientras que $\eta>0$ Controla el peso de la cola. La construcción ([anciano\]) se basa en una mezcla de escalas de (una versión reparametrizada de) el modelo de Matérn que involucra la distribución gamma inversa.[106]han demostrado que esta clase es particularmente útil para problemas de extrapolación donde predominan grandes distancias.

## Núcleos poliarmónicos {#SecPoly}

Nuestro catálogo de mejoras del modelo Matérn termina con *núcleos poliarmónicos*, definidos como

$$
\label{eqKmd}
H_{\nu,d}(x):=
\left\{
\begin{array}{ll}
x^{2\nu-d}\log x &\hbox{ para } 2\nu-d \in 2\mathbb{Z}\\
x^{2\nu-d}& \hbox{ else }
\end{array} 
\right\}
$$

hasta la señal $(-1)^{\lfloor \nu-d/2 \rfloor +1}$ . En función de $x=\|\boldsymbol{x}\|$ , $\boldsymbol{x} \in \mathbb{R}^d$ , el núcleo de Matérn ${\cal M}_{\nu-d/2,1}$ comienza con potencias pares de $x$ seguido por $H_{\nu,d}$ , y en este sentido los dos modelos están relacionados. Hasta un factor constante, la transformada generalizada de Fourier de $H_{\nu,d}(\|x\|)$ en $\mathbb{R}^d$ es $\|\omega\|^{-2\nu}$ , y luego un parámetro de escala es simplemente otro factor constante. Esto hace que la interpolación basada en núcleo por poliarmónicos sea independiente de la escala. Compare con ([stein1\]) para ver la conexión con ${\cal M}_{\nu-d/2,\alpha}$ en el espacio de Fourier.[150]proporciona una conexión formal entre núcleos poliarmónicos, para los cuales también se utiliza el nombre de funciones de covarianza *ley de potencia*, y el modelo de Matérn. Los núcleos poliarmónicos son *definidos condicionalmente positivos* de orden $\lfloor \nu -d/2 \rfloor+1$ ; para una definición técnica ver[166]. En lugar de espacios de Hilbert, los núcleos poliarmónicos generan *espacios Beppo--Levi*, que comparten similitudes con los espacios de Sobolev, módulo en el que se debe agregar un espacio polinomial adicional para permitir la predicción (Sección [3](#Sec3)) y la interpolación (Sección [6.1](#SecNAaAT)); ver[166]. En general, los núcleos poliarmónicos surgen como covarianzas en campos gaussianos *fraccionales*, incluidas las formas de movimiento browniano.[104 Theorem 3.3].

A continuación, nuestra atención se centra en una discusión crítica sobre si tales mejoras al modelo de Matérn son necesarias.
